name: VEdge_Detector11
dependencies:
  - spyder
  - python=3.7
  - numpy=1.18.5
  - rasterio=1.1.1
  - GDAL=3.0.2
  - Keras=2.3.1
  - scikit-image=0.16.2
  - Pillow=8.1.0
  - pip=19.0
  - pip:
    - Tensorflow==2.2








